---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crd.streamdal.com
  resources:
  - streamdalconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.streamdal.com
  resources:
  - streamdalconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - crd.streamdal.com
  resources:
  - streamdalconfigs/status
  verbs:
  - get
  - patch
  - update
