replicaCount: 1

images:
  logProcessor:
    repository: streamdal/log-processor
    pullPolicy: Always
    tag: "a3c4787cc"
  logstash:
    repository: logstash
    tag: "7.17.20"
    pullPolicy: IfNotPresent

service:
  logProcessorPort: 6000
  logstashPort: 6001

persistence:
  logs:
    size: 10Gi
    storageClass: efs-sc

config:
  elasticsearchHosts: ""
  xpackMonitoringEnabled: false
  STREAMDAL_LOG_PROCESSOR_STREAMDAL_SERVER_ADDRESS: "server.vector.svc.cluster.local:8082"
  STREAMDAL_LOG_PROCESSOR_LISTEN_ADDR: "0.0.0.0:6000"
  STREAMDAL_LOG_PROCESSOR_LOGSTASH_ADDR: "127.0.0.1:6001"
  STREAMDAL_LOG_PROCESSOR_STREAMDAL_TOKEN: "1234"
  STREAMDAL_LOG_PROCESSOR_LOG_LEVEL: "ERROR"

logrotate:
  name: logrotate-deployment
  replicas: 1
  image: blacklabelops/logrotate
  env:
    LOGS_DIRECTORIES: "/var/log/pods"
    LOGROTATE_SIZE: "100M"
    CRON_SCHEDULE: "*/5 * * * *"

resources:
  logProcessor:
    limits:
      cpu: "2000m"
      memory: "1Gi"
    requests:
      cpu: "1500m"
      memory: "512Mi"
  logstash:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
