apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-logstash-config
data:
  logstash.conf: |
    input {
      file {
        path =>  "/var/log/pods/*/*/*.log"
        start_position => "beginning"
        sincedb_path => "/var/sincedb.db"  # Provide a valid path on your system
        type => "file"
      }
    }
    
    output {
      if [type] == "file" {
        tcp {
          host => "127.0.0.1"
          port => 6000
          codec => json_lines
          reconnect_interval => 10
        }
      }
    }
    
    input {
      tcp {
        port => 6001
        codec => json
        type => "processor"
      }
    }
    
    filter {
      if [type] == "processor" {
        grok {
            match => { "path" => "/var/log/pods/%{DATA:container}/%{DATA:service}/%{GREEDYDATA:filename}" }
        }
      }
    }
    
    output {
      if [type] == "processor" {
        file {
          path => "/logs/%{container}/%{service}/%{filename}"
          codec => line { format => "%{message}" }
        }
      }
    }
