apiVersion: v1
kind: ConfigMap
metadata:
  name: logrotate-config
  namespace: vector
data:
  logrotate.conf: |
    /logs/*/*/*.log {
        daily
        size {{ .Values.logrotate.env.LOGROTATE_SIZE }}
        dateext
        dateformat -%Y-%m-%d-%H-%M
        rotate 3
        maxage 3
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
    }