apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.logrotate.name }}
  labels:
    app: {{ .Values.logrotate.name }}
spec:
  replicas: {{ .Values.logrotate.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.logrotate.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.logrotate.name }}
    spec:
      containers:
      - name: logrotate
        image: skymatic/logrotate:latest
        env:
        - name: CRON_SCHEDULE
          value: "{{ .Values.logrotate.env.CRON_SCHEDULE }}"
        volumeMounts:
          - name: logs
            mountPath: /logs
          - name: logrotate-config
            mountPath: /etc/logrotate.conf
            subPath: logrotate.conf
            readOnly: true
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logs-pvc
        - name: logrotate-config
          configMap:
            name: logrotate-config
