apiVersion: crd.streamdal.com/v1
kind: StreamdalConfig
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: sample-config
spec:
  serverAddress: ":8082"
  serverAuth: "1234"
  configs:
    - name: "config with audiences"
      config: >
        {
          "audiences": [
            {
              "serviceName": "service1",
              "operationType": "OPERATION_TYPE_CONSUMER",
              "operationName": "operationName1",
              "componentName": "componentName1"
            },
            {
              "serviceName": "service3",
              "operationType": "OPERATION_TYPE_CONSUMER",
              "operationName": "operationName3",
              "componentName": "componentName3"
            }
          ]
        }
