apiVersion: crd.streamdal.com/v1
kind: StreamdalConfig
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: sample-config
spec:
  serverAddress: ":8082"
  serverAuth: "1234"
  configs:
    - name: "config with audiences"
      config: >
        {
          "audiences": [
            {
              "serviceName": "service5",
              "operationType": "OPERATION_TYPE_CONSUMER",
              "operationName": "operationName5",
              "componentName": "componentName5"
            }
          ],
          "notifications": [
            {
              "id": "c746e19d-171c-4521-9a2d-bb456624acaa-1",
              "name": "Test slack Integration",
              "type": "NOTIFICATION_TYPE_SLACK",
              "slack": {
                "botToken": "test-token",
                "channel": "test-channel"
              }
            },
            {
              "id": "c746e19d-171c-4521-9a2d-bb456624aca-2",
              "name": "Test slack Integration",
              "type": "NOTIFICATION_TYPE_SLACK",
              "slack": {
                "botToken": "test-token",
                "channel": "test-channel"
              }
            }
          ]
        }
