apiVersion: crd.streamdal.com/v1
kind: StreamdalConfig
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: streamdalconfig-sample
spec:
  serverAddress: "streamdal-address"
  serverAuth: "streamdal-auth"
  configs:
    - name: "config1"
      config: >
        {
          "foo": "bar"
        }
    - name: "config2"
      config: >
        {
          "foo": "baz"
        }
