apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "streamdal-operator.fullname" . }}-manager-role
  labels:
  {{- include "streamdal-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - crd.streamdal.com
  resources:
  - streamdalconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.streamdal.com
  resources:
  - streamdalconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - crd.streamdal.com
  resources:
  - streamdalconfigs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "streamdal-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
  {{- include "streamdal-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "streamdal-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "streamdal-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'