name: Log Processor - Pull Request

on:
  pull_request:
    paths:
      - 'apps/log-processor/**'
      - '.github/workflows/apps-log-processor-pr.yml'

defaults:
  run:
    working-directory: ./apps/log-processor

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '~1.22'
    - name: Install C dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y libc6-dev
    - uses: actions/checkout@v2

    - name: Test
      env:
        CGO_ENABLED: 1
      run: |
        make test
