name: Protos - Pull Request

on:
  pull_request:
    paths:
      - 'libs/protos/**'
      - '.github/workflows/libs-protos-pr.yml'

defaults:
  run:
    working-directory: ./libs/protos

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install protolint
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: yoheimuta/protolint
          tag: v0.49.7

      - name: Run linter
        run: |
          make lint

      - name: Compile protos
        run: |
          make generate/go
          make generate/rust
          make generate/ts
          make generate/protoset
          make generate/python
          make generate/ruby
