name: Wasm - Pull Request

on:
  pull_request:
    paths:
      - 'libs/wasm/**'
      - 'libs/wasm-detective/**'
      - 'libs/wasm-transform/**'
      - '.github/workflows/libs-wasm-pr.yml'

defaults:
  run:
    working-directory: ./libs/wasm

jobs:
  build:
    name: Build all WASM
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: build
        run: |
          rustup target add wasm32-wasi
          cargo install wasm-opt
          make build
      - uses: actions/upload-artifact@master
        with:
          name: wasm-test-artifact
          path: libs/wasm/build
  test:
    name: Test build
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        funcs: ["detective", "httprequest", "inferschema", "kv", "transform", "validjson"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: wasm-test-artifact
          path: libs/wasm/build
      - name: modsurfer validate
        uses: dylibso/modsurfer-validate-action@main
        with:
            path: libs/wasm/build/${{ matrix.funcs }}.wasm
            check: libs/wasm/validation/${{ matrix.funcs }}.wasm.mod.yaml
  test-go-sdk:
    name: Test with Go SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: wasm-test-artifact
          path: libs/wasm/build
      - uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: WASM interface tests via Go
        working-directory: ./sdks/go
        env:
          WASM_DIR: ../../libs/wasm/build
        run: |
          go test -v ./...

  test-ruby-sdk:
    name: Test with Ruby SDK
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: WASM interface tests via Ruby
        working-directory: ./sdks/ruby
        env:
          WASM_DIR: ../../libs/wasm/build
        run: |
          bundle exec rake test
