name: SDK Ruby - Pull Request

on:
  pull_request:
    paths:
      - 'sdks/ruby/**'
      - '.github/workflows/sdks-ruby-pr.yml'

defaults:
  run:
    working-directory: ./sdks/ruby

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.0", "3.1", "3.2", "3.3"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: bundle exec rake test

  coverage:
    name: Generate code coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run coverage
        run: |
            bundle exec rake test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ruby-sdk
          files: coverage/coverage.xml