name: SDK Ruby - Release

on:
  push:
    branches:
      - main
    paths:
      - 'sdks/ruby/**'
      - '.github/workflows/sdks-ruby-release.yml'

defaults:
  run:
    working-directory: ./sdks/ruby

jobs:
#  coverage:
#    name: Generate code coverage report
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Set up Ruby 3.3
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 3.3
#
#      - name: Install dependencies
#        run: |
#          gem install bundler
#          bundle install
#      - name: Install Code Climate reporter
#        run: |
#          sudo curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#          sudo chmod +x ./cc-test-reporter
#          ./cc-test-reporter before-build
#      - name: Run coverage
#        run: |
#          bundle exec rake test
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v4.0.1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          flags: ruby-sdk
#          files: sdks/ruby/coverage/coverage.xml
  build:
    name: Tag and Release
    if: ${{ !contains(github.event.head_commit.message, 'norelease') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate new tag (dry run)
        uses: mathieudutour/github-tag-action@v6.1
        id: get_new_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          fetch_all_tags: true
          tag_prefix: "sdks/ruby/v"

      - name: Inject version into streamdal.gemspec and lib/streamdal.rb
        run: |
          sed -i "s/version = \".*\"/version = \"${{ steps.get_new_version.outputs.new_version }}\"/" streamdal.gemspec
          sed -i "s/library_version = \".*\"/library_version = \"${{ steps.get_new_version.outputs.new_version }}\"/" lib/streamdal.rb

      # We do this because other jobs might have written to the repo while this
      # job was running and making local changes; without this pull step, we
      # might run into an error during auto-commit.
      - name: Pull latest changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --depth=10

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto_commit
        with:
          commit_message: Bumped version in streamdal.gemspec to ${{ steps.get_new_version.outputs.new_version }}

      # .. and now create the actual tag (will be the same as the dry run)
      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        id: create_tag
        with:
          commit_sha: ${{ steps.auto_commit.outputs.commit_hash }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get_new_version.outputs.new_version }}
          tag_prefix: "sdks/ruby/v"

      - name: Build ruby gem
        run: |
          gem build streamdal.gemspec
          gem push streamdal-${{ steps.get_new_version.outputs.new_version }}.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

