name: SDK Go - Release

on:
  push:
    branches:
      - main
    paths:
      - 'sdks/go/**'
      - '.github/workflows/sdks-go-release.yml'

defaults:
  run:
    working-directory: ./sdks/go

jobs:
  build:
    name: Tag and Release
    if: ${{ !contains(github.event.head_commit.message, 'norelease') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate new tag (dry run)
        uses: mathieudutour/github-tag-action@v6.1
        id: get_new_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          tag_prefix: "sdks/go/v"

      - name: Inject version into register.go
        run: |
          sed -i 's/LibraryVersion:.*/LibraryVersion: "${{ steps.get_new_version.outputs.new_version }}",/' register.go

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bumped version in register.go to ${{ steps.get_new_version.outputs.new_version }}

      # .. and now create the actual tag (will be the same as the dry run)
      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        id: create_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get_new_version.outputs.new_version }}
          tag_prefix: "sdks/go/v"

