name: SDK Ruby - Pull Request

on:
  pull_request:
    paths:
      - 'sdks/ruby/**'
      - '.github/workflows/sdks-ruby-pr.yml'

defaults:
  run:
    working-directory: ./sdks/ruby

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.0", "3.1", "3.2", "3.3"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: bundle exec rake test

  coverage:
    name: Generate code coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Install Code Climate reporter
        run: |
          sudo curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          sudo chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Run coverage
        run: |
            bundle exec rake test
      - name: Upload coverage information
        run: |
          ./cc-test-reporter format-coverage -t simplecov
          GIT_BRANCH="${GITHUB_HEAD_REF}" ./cc-test-reporter after-build \
            -r ${{ secrets.CC_TEST_REPORTER_ID }} \
            -t simplecov
